import type { WorkflowDecision, WorkflowHandoff, WorkflowStepDefinition } from "./types";

export const mockWorkflowSteps: WorkflowStepDefinition[] = [
  {
    stepIndex: 0,
    category: "setup",
    title: "Demo staged and ready",
    shortLabel: "Ready",
    description: "The incident packet is loaded, but no agent has posted into the shared room yet.",
    phase: "intake",
    status: "open",
    severity: "medium",
    decisionGate: "none",
    activeAgentIds: ["agent-commander"],
    completedAgentIds: [],
    waitingAgentIds: ["agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance", "agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: [],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "This is the pre-run state: the app is demoable before any live API dependency is connected.",
    bandProof: "The next step creates the shared incident room that all agents coordinate through.",
  },
  {
    stepIndex: 1,
    category: "room",
    title: "Band incident room opened",
    shortLabel: "Room opened",
    description: "Commander establishes the shared coordination room and registers specialist agents.",
    messageId: "msg-001",
    phase: "triage",
    status: "triaging",
    severity: "high",
    decisionGate: "none",
    activeAgentIds: ["agent-commander"],
    completedAgentIds: [],
    waitingAgentIds: ["agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance", "agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: [],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "Band is visible immediately: this is not a final output channel; it is the incident room.",
    bandProof: "Room creation, agent registration, and shared case context begin in the coordination layer.",
  },
  {
    stepIndex: 2,
    category: "assignment",
    title: "Specialist tasks assigned",
    shortLabel: "Tasks assigned",
    description: "Commander delegates log review, code/config review, indicator assessment, and policy review.",
    messageId: "msg-002",
    phase: "evidence_collection",
    status: "investigating",
    severity: "high",
    decisionGate: "none",
    activeAgentIds: ["agent-forensics", "agent-code-review", "agent-threat-intel", "agent-risk-compliance"],
    completedAgentIds: [],
    waitingAgentIds: ["agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: [],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "This is where single-agent demos start to fall apart; Sentinel Relay splits responsibility explicitly.",
    bandProof: "The task assignment message becomes the shared contract each specialist responds to.",
  },
  {
    stepIndex: 3,
    category: "evidence",
    title: "Suspicious token usage identified",
    shortLabel: "Log finding",
    description: "Forensics posts an evidence-backed finding from API gateway and auth logs.",
    messageId: "msg-003",
    phase: "evidence_collection",
    status: "investigating",
    severity: "high",
    decisionGate: "none",
    activeAgentIds: ["agent-forensics", "agent-threat-intel"],
    completedAgentIds: ["agent-commander"],
    waitingAgentIds: ["agent-code-review", "agent-risk-compliance", "agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly"],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "The finding is not just a paragraph: it links to concrete evidence references.",
    bandProof: "Forensics hands evidence to Threat Intel and Risk for verification rather than declaring the final answer alone.",
  },
  {
    stepIndex: 4,
    category: "verification",
    title: "Indicator confidence qualified",
    shortLabel: "Intel check",
    description: "Threat Intel raises concern but prevents overclaiming based on weak indicator data.",
    messageId: "msg-004",
    phase: "evidence_collection",
    status: "investigating",
    severity: "high",
    decisionGate: "none",
    activeAgentIds: ["agent-threat-intel", "agent-code-review"],
    completedAgentIds: ["agent-forensics"],
    waitingAgentIds: ["agent-risk-compliance", "agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket"],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "The system is careful: suspicious behavior is elevated, but not overstated.",
    bandProof: "A verification message updates shared confidence before Risk makes a policy decision.",
  },
  {
    stepIndex: 5,
    category: "evidence",
    title: "Recent diff likely exposed token material",
    shortLabel: "Code finding",
    description: "Code Review connects the runtime anomaly to a Friday deployment change.",
    messageId: "msg-005",
    phase: "hypothesis_review",
    status: "investigating",
    severity: "high",
    decisionGate: "none",
    activeAgentIds: ["agent-code-review", "agent-risk-compliance"],
    completedAgentIds: ["agent-forensics", "agent-threat-intel"],
    waitingAgentIds: ["agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff"],
    visibleTaskIds: [],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "This is the Track 2 value inside Track 3: software review supports the regulated decision.",
    bandProof: "Code Review hands root-cause evidence to Risk & Compliance instead of acting on production alone.",
  },
  {
    stepIndex: 6,
    category: "challenge",
    title: "Risk challenges customer-impact claim",
    shortLabel: "Challenge",
    description: "Risk & Compliance blocks unsupported customer notification until data scope is proven.",
    messageId: "msg-006",
    phase: "risk_review",
    status: "awaiting_approval",
    severity: "high",
    decisionGate: "human_required",
    activeAgentIds: ["agent-risk-compliance", "agent-commander"],
    completedAgentIds: ["agent-forensics", "agent-threat-intel", "agent-code-review"],
    waitingAgentIds: ["agent-remediation"],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff", "ev-policy-approval"],
    visibleTaskIds: [],
    unresolvedChallengeIds: ["msg-006"],
    openApprovalRequestIds: [],
    judgeCallout: "This is the key winning moment: agents do not simply agree; one agent challenges the conclusion.",
    bandProof: "The challenge is preserved as structured coordination state, not buried in chat text.",
  },
  {
    stepIndex: 7,
    category: "approval",
    title: "Human approval requested",
    shortLabel: "Approval gate",
    description: "Commander requests approval for containment while customer notification remains held.",
    messageId: "msg-007",
    phase: "human_approval",
    status: "awaiting_approval",
    severity: "high",
    decisionGate: "human_required",
    activeAgentIds: ["agent-commander", "human-security-lead"],
    completedAgentIds: ["agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance"],
    waitingAgentIds: [],
    blockedAgentIds: ["agent-remediation"],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff", "ev-policy-approval"],
    visibleTaskIds: [],
    unresolvedChallengeIds: ["msg-006"],
    openApprovalRequestIds: ["approval-001"],
    judgeCallout: "The workflow refuses to auto-execute high-impact production containment.",
    bandProof: "The approval request is a first-class Band coordination event.",
  },
  {
    stepIndex: 8,
    category: "approval",
    title: "Containment approved, disclosure deferred",
    shortLabel: "Approved",
    description: "Human security lead approves containment but explicitly does not approve customer notification.",
    messageId: "msg-008",
    phase: "containment",
    status: "approved_for_containment",
    severity: "high",
    decisionGate: "approved",
    activeAgentIds: ["agent-remediation"],
    completedAgentIds: ["agent-commander", "agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance", "human-security-lead"],
    waitingAgentIds: [],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff", "ev-policy-approval", "ev-human-approval"],
    visibleTaskIds: ["rem-001"],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "The human decision has scope: approved actions and explicitly not-approved actions are separated.",
    bandProof: "The decision becomes durable audit context for the remediation agent.",
  },
  {
    stepIndex: 9,
    category: "remediation",
    title: "Containment and fix plan prepared",
    shortLabel: "Remediation",
    description: "Remediation creates actionable tasks with acceptance criteria, tests, and rollback notes.",
    messageId: "msg-009",
    phase: "remediation",
    status: "remediating",
    severity: "high",
    decisionGate: "approved",
    activeAgentIds: ["agent-remediation"],
    completedAgentIds: ["agent-commander", "agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance", "human-security-lead"],
    waitingAgentIds: [],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff", "ev-policy-approval", "ev-human-approval"],
    visibleTaskIds: ["rem-001", "rem-002", "rem-003", "rem-004"],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "Remediation is constrained by the human-approved action scope.",
    bandProof: "The remediation handoff consumes prior evidence, challenge resolution, and approval context.",
  },
  {
    stepIndex: 10,
    category: "report",
    title: "Audit-ready report generated",
    shortLabel: "Report ready",
    description: "The report cites messages, evidence, approvals, unresolved questions, and remediation tasks.",
    messageId: "msg-010",
    phase: "reporting",
    status: "report_ready",
    severity: "high",
    decisionGate: "approved",
    activeAgentIds: ["agent-commander"],
    completedAgentIds: ["agent-commander", "agent-forensics", "agent-threat-intel", "agent-code-review", "agent-risk-compliance", "agent-remediation", "human-security-lead"],
    waitingAgentIds: [],
    blockedAgentIds: [],
    visibleEvidenceIds: ["ev-api-spike", "ev-auth-anomaly", "ev-customer-ticket", "ev-code-diff", "ev-policy-approval", "ev-human-approval"],
    visibleTaskIds: ["rem-001", "rem-002", "rem-003", "rem-004"],
    unresolvedChallengeIds: [],
    openApprovalRequestIds: [],
    judgeCallout: "The final output is traceable back to the exact coordination stream that produced it.",
    bandProof: "The audit trail is not invented afterward; it is assembled from the shared coordination record.",
  },
];

export const mockWorkflowHandoffs: WorkflowHandoff[] = [
  {
    id: "handoff-room-to-specialists",
    fromAgentId: "agent-commander",
    toAgentId: "agent-forensics",
    title: "Commander → Forensics",
    summary: "Review API gateway and auth logs for suspicious token activity.",
    visibleAtStep: 2,
    evidenceIds: [],
    status: "locked",
  },
  {
    id: "handoff-forensics-to-intel",
    fromAgentId: "agent-forensics",
    toAgentId: "agent-threat-intel",
    title: "Forensics → Threat Intel",
    summary: "Verify whether suspicious region/IP behavior is enough to raise confidence.",
    visibleAtStep: 3,
    evidenceIds: ["ev-api-spike", "ev-auth-anomaly"],
    status: "locked",
  },
  {
    id: "handoff-code-to-risk",
    fromAgentId: "agent-code-review",
    toAgentId: "agent-risk-compliance",
    title: "Code Review → Risk",
    summary: "Use deployment diff evidence to evaluate root-cause and policy obligations.",
    visibleAtStep: 5,
    evidenceIds: ["ev-code-diff"],
    status: "locked",
  },
  {
    id: "handoff-risk-to-human",
    fromAgentId: "agent-risk-compliance",
    toAgentId: "human-security-lead",
    title: "Risk → Human Lead",
    summary: "Escalate containment approval while holding customer notification pending scope proof.",
    visibleAtStep: 7,
    evidenceIds: ["ev-api-spike", "ev-code-diff", "ev-policy-approval"],
    status: "locked",
  },
  {
    id: "handoff-approval-to-remediation",
    fromAgentId: "human-security-lead",
    toAgentId: "agent-remediation",
    title: "Human Lead → Remediation",
    summary: "Proceed only with approved containment scope: revoke token, rotate secrets, and fix config handling.",
    visibleAtStep: 8,
    evidenceIds: ["ev-human-approval"],
    status: "locked",
  },
];

export const mockWorkflowDecisions: WorkflowDecision[] = [
  {
    id: "decision-001",
    title: "Can the system call this a customer breach?",
    summary: "Risk challenges the conclusion until accessed endpoint scope is confirmed.",
    owner: "Risk & Compliance Agent",
    status: "locked",
    visibleAtStep: 6,
  },
  {
    id: "decision-002",
    title: "Can containment proceed?",
    summary: "Human Security Lead must approve production containment before remediation can mark tasks approved.",
    owner: "Human Security Lead",
    status: "locked",
    visibleAtStep: 7,
    resolvedAtStep: 8,
  },
  {
    id: "decision-003",
    title: "Should customers be notified now?",
    summary: "Customer notification is explicitly deferred because the demo has not proven customer data scope.",
    owner: "Human Security Lead + Risk & Compliance",
    status: "locked",
    visibleAtStep: 8,
  },
];

export function getWorkflowStep(stepIndex: number): WorkflowStepDefinition {
  const boundedStep = Math.max(0, Math.min(stepIndex, mockWorkflowSteps.length - 1));
  const step = mockWorkflowSteps[boundedStep];
  if (!step) {
    throw new Error(`No workflow step exists for index ${boundedStep}.`);
  }
  return step;
}
