// The canonical schema source now lives in packages/schemas.
// This file intentionally re-exports those types so existing web imports stay stable.
// New code should prefer importing from "@/lib/types" inside the web app and from
// "@sentinel-relay/schemas" in shared packages or external tools.

export type {
  AgentAssignment,
  AgentCapability,
  AgentKind,
  AgentMessage,
  AgentMessagePayload,
  AgentMessageType,
  AgentProfile,
  ApprovalDecision,
  ApprovalDecisionValue,
  ApprovalRequest,
  ApprovalStatus,
  BandEnvelope,
  CaseId,
  ChallengePayload,
  CollaborationMode,
  ConfidenceBand,
  ConfidenceScore,
  DecisionGate,
  DemoIncident,
  EvidenceBundle,
  EvidenceId,
  EvidenceKind,
  EvidenceReference,
  EvidenceReferencePointer,
  EvidenceSensitivity,
  FieldValidationIssue,
  FinalReport,
  FindingPayload,
  HandoffPayload,
  IncidentCase,
  IncidentPhase,
  IncidentStateSnapshot,
  IncidentStatus,
  ISODateTimeString,
  MessageId,
  MessageVisibility,
  RemediationPlan,
  RemediationTask,
  RemediationTaskStatus,
  ReportSection,
  ReportSectionType,
  RiskAssessmentPayload,
  RiskSignal,
  RoomId,
  Severity,
  TaskAssignmentPayload,
  TaskId,
  TaskStatus,
  TimelineEvent,
  ValidationResult,
} from "@sentinel-relay/schemas";

export {
  PRODUCT_NAME,
  SCHEMA_VERSION,
  agentCapabilityValues,
  agentStatusValues,
  approvalDecisionValues,
  approvalStatusValues,
  collaborationModeValues,
  confidenceBandValues,
  decisionGateValues,
  evidenceKindValues,
  evidenceSensitivityValues,
  incidentPhaseValues,
  incidentStatusValues,
  isAgentCapability,
  isAgentStatus,
  isApprovalDecisionValue,
  isApprovalStatus,
  isCollaborationMode,
  isConfidenceBand,
  isConfidenceScore,
  isDecisionGate,
  isEvidenceKind,
  isEvidenceSensitivity,
  isIncidentPhase,
  isIncidentStatus,
  isIsoDateTime,
  isMessageType,
  isReportSectionType,
  isSeverity,
  isTaskStatus,
  messageTypeValues,
  reportSectionTypeValues,
  severityValues,
  taskStatusValues,
  validateAgentMessageShape,
  validateDemoIncidentShape,
} from "@sentinel-relay/schemas";
